application/api/urls.py
from django.urls import path
from . import views

from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name = 'api'
urlpatterns = [
    path('v1', views.ApiV1.get, name='apiv1'),
    path('v2', views.ApiV2.as_view(), name='apiv2'),
    path('v3', views.ApiV3.as_view(), name='apiv3'),
    path('v4', views.ApiV4.as_view(), name='apiv4'),
    path('auth/', include('rest_framework.urls')),
    path('rest/', include(router.urls)),
]

application/theater/urls.py
from django.urls import path
from . import views

app_name = 'theater'
urlpatterns = [
    path('', views.Theater.as_view(), name='theater'),
    path('organization', views.Organization.as_view(), name='organization'),
    #path('<int:pk>/', views.Detail.as_view(), name='detail'),
]

application/theater/models.py
from django.db import models

# Create your models here.

application/theater/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import *

class Theater(generic.ListView):
    template_name = 'theater/theater.html'
    context_object_name = 'latest_theater_list'

    def get_queryset(self):
        """
        return set of datas if needed
        """
        return ''

class Organization(generic.ListView):
    template_name = 'theater/organization.html'
    context_object_name = 'latest_organization_list'

    def get_queryset(self):
        """
        return set of datas if needed
        """
        return ''

application/theater/templates/theater/organization.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Theater Organizations | {{ settings.APP_NAME_TEXT }}{% endblock %}
{% block styles %}{% endblock %}

{% block content %}
<!-- begin #content -->
<div id="content" class="content">
	<!-- begin breadcrumb -->
	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item"><a href="{% url 'theater:theater' %}">Theater</a></li>
		<li class="breadcrumb-item active">Theater Organizations</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Theater Organizations<small>List of theater organizations</small></h1>
	<!-- end page-header -->
	<!-- begin row -->
	<div class="row">
	    Theater Organizations Page
	</div>
</div>
<!-- end #content -->
{% endblock %}

{% block scripts %}{% endblock %}

application/theater/templates/theater/theater.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Theaters | {{ settings.APP_NAME_TEXT }}{% endblock %}
{% block styles %}{% endblock %}

{% block content %}
<!-- begin #content -->
<div id="content" class="content">
	<!-- begin breadcrumb -->
	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item active">Theaters</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Theaters<small>List of theaters</small></h1>
	<!-- end page-header -->
	<!-- begin row -->
	<div class="row">
	    Theaters Page
	</div>
</div>
<!-- end #content -->
{% endblock %}

{% block scripts %}{% endblock %}