application/api/urls.py
from django.urls import path
from . import views

from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name = 'api'
urlpatterns = [
    path('v1', views.ApiV1.get, name='apiv1'),
    path('v2', views.ApiV2.as_view(), name='apiv2'),
    path('v3', views.ApiV3.as_view(), name='apiv3'),
    path('v4', views.ApiV4.as_view(), name='apiv4'),
    path('auth/', include('rest_framework.urls')),
    path('rest/', include(router.urls)),
]

application/asset/urls.py
from django.urls import path
from . import views

app_name = 'asset'
urlpatterns = [
    path('coming-soon', views.ComingSoon.as_view(), name='coming-soon'),
    path('blocked-screening', views.BlockedScreening.as_view(), name='blocked-screening'),
    #path('<int:pk>/', views.Detail.as_view(), name='detail'),
]

application/client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns = [
    path('', views.Client.as_view(), name='client'),
    #path('<int:pk>/', views.Detail.as_view(), name='detail'),
]

application/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
	path('login/', views.Login.as_view(), name='login'),
	path('signoff/', views.logout_view, name='logout'),
	path('signup/', views.Signup.as_view(), name='signup'),
	path('success_signup/', views.SuccessSignup.as_view(), name='success_signup'),
	path('activate/<uidb64>/<token>/', views.activate, name='activate_email'),
    path('password/reset/', views.ResetPassword.as_view(), name='password_reset'),
    path('password/change/<token>/', views.ChangePassword.as_view(), name='password_change'),
]

application/feed/urls.py
from django.urls import path
from . import views

app_name = 'feed'
urlpatterns = [
    path('', views.Feed.as_view(), name='feed'),
    #path('<int:pk>/', views.Detail.as_view(), name='detail'),
]

application/movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'
urlpatterns = [
    path('', views.Movie.as_view(), name='movie'),
    path('movie/title', views.MovieTitle.as_view(), name='movie-title'),
    path('movie/title/lookup', views.MovieTitleLookup.as_view(), name='movie-title-lookup'),
    #path('<int:pk>/', views.Detail.as_view(), name='detail'),
]

application/core/models.py
import datetime
from django.db import models
from django.utils import timezone

class PasswordResets(models.Model):
	email = models.CharField(max_length=255)
	token = models.CharField(max_length=255)
	created_at 	= models.DateTimeField(timezone.now())

application/core/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.validators import validate_email
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if not user or not user.is_active:
                raise forms.ValidationError("Sorry, Invalid username or password. Please try again.")

        return self.cleaned_data

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class PasswordResetForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')

        if email and not User.objects.filter(email=email).exists():
            raise forms.ValidationError("We could'nt find that email address, Please try again.")

        return self.cleaned_data

class ChangePasswordForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, help_text='Required. Inform a valid and existing email address.')
    password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("We could'nt find that email address, Please try again!")
        if password != confirm_password:
            raise forms.ValidationError("Password not match. Please try again!")

        return self.cleaned_data

application/core/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import View
from django.utils import timezone
#from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.models import User
from .forms import *
from .models import *
from .core_helpers import *

#class handing for account login
class Login(View):
    template_name='core/login.html'

    def get(self, request, *args, **kwargs):
        form  = LoginForm()

        if request.user.is_authenticated:
            return redirect('/')

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = LoginForm(request.POST or None)
        username = request.POST['username']
        password = request.POST['password']

        if form.is_valid():
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)

                return HttpResponseRedirect('/')

        return render(request, self.template_name, {'form': form})

#class handing for account signup
class Signup(View):
    template_name = 'core/signup.html'

    def get(self, request, *args, **kwargs):
        form = SignupForm()
        if request.user.is_authenticated:
            return redirect('/')

        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = SignupForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            send_email(request, user, {}, 'Account activation email.', 'core/mail/account_activation.html')
            messages.success(request, 'Successfully registered, Please check activation link on your email.')

            return redirect('/accounts/success_signup/?email='+user.email)

        return render(request, self.template_name, {'form': form})

#class handling for successfull signup
class SuccessSignup(View):
    template_name = 'core/success_signup.html'
    
    def get(self, request, *args, **kwargs):
        email = request.GET['email']
        get_object_or_404(User, email=email)
        user =  User.objects.get(email=email)

        if user.is_active:
            raise Http404

        return render(request, self.template_name, {'email': email})

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        get_object_or_404(User, email=email)
        user =  User.objects.get(email=email)

        if user.is_active:
            raise Http404

        user = User.objects.get(email=email)
        send_email(request, user, {},'Account activation email.', 'core/mail/account_activation.html')
        messages.success(request, "Activation link successfully sent to your email "+email)

        return render(request, self.template_name, {'email': email})

#class handling for resetting password
class ResetPassword(View):
    template_name = 'core/password/reset_password.html'

    def get(self, request, *args, **kwargs):
        form = PasswordResetForm()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = PasswordResetForm(request.POST or None)
        email = request.POST['email']

        if form.is_valid():
            if User.objects.filter(email=email).exists():
                user = User.objects.get(email=email)
                token = generate_token.make_token(User.objects.get(email=email))
                email = email
                created_at = timezone.now()

                if PasswordResets.objects.filter(email=email).exists():
                    pr = PasswordResets.objects.get(email=email)
                    pr.email = email
                    pr.token = token
                    pr.created_at = created_at
                    pr.save()
                else:
                    pr = PasswordResets(email=email, token=token, created_at=created_at)
                    pr.save()

                messages.info(request, "Password reset link has been sent to your email.")
                data = {'token': token }
                send_email(request, user, {'token': token,},'Password reset link.', 'core/mail/password_reset.html')

        return render(request, self.template_name, {'form': form})

#class handling for resetting password
class ChangePassword(View):
    template_name = 'core/password/change_password.html'

    def get(self, request, token, *args, **kwargs):
        form = ChangePasswordForm()
        get_object_or_404(PasswordResets, token=token)

        return render(request, self.template_name, {'form': form})

    def post(self, request, token, *args, **kwargs):
        form = ChangePasswordForm(request.POST or None)
        email = request.POST['email']
        get_object_or_404(PasswordResets, token=token)

        if form.is_valid():
            user = User.objects.get(email=email)
            user.set_password(request.POST['password'])
            user.save()

            PasswordResets.objects.get(token=token).delete()
            messages.success(request, "You've successfully updated your password. You may now login with your new password!")

            return HttpResponseRedirect('/accounts/login/')

        return render(request, self.template_name, {'form': form})

#method for account activation via email link
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64).decode())
        user = User.objects.get(pk=uid)

        if user.is_active:
            raise Http404
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "You've Successfully activated your account.")

        return redirect('/')
    else:
        return render(request, 'account_activation_invalid.html')

#method for logout
@login_required
def logout_view(request):
    logout(request)

    return HttpResponseRedirect('/accounts/login')

application/core/templates/layout/includes/footer.html
<!-- begin scroll to top btn -->
<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
<!-- end scroll to top btn -->

application/core/templates/layout/includes/header.html
{% load staticfiles %}
<!-- begin #header -->
<div id="header" class="header navbar-default">
	<!-- begin navbar-header -->
	<div class="navbar-header">
		<a href="/" class="navbar-brand"><!-- <span class="navbar-logo"></span>  --><b>GMOVIES</b> Admin</a>
		<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<!-- end navbar-header -->
	
	<!-- begin header-nav -->
	<ul class="navbar-nav navbar-right">
		<li>
			<form class="navbar-form">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Enter keyword" />
					<button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
				</div>
			</form>
		</li>
		<li class="dropdown">
			<a href="javascript:;" data-toggle="dropdown" class="dropdown-toggle f-s-14">
				<i class="fa fa-bell"></i>
				<span class="label">5</span>
			</a>
			<ul class="dropdown-menu media-list dropdown-menu-right">
				<li class="dropdown-header">NOTIFICATIONS (5)</li>
				<li class="media">
					<a href="javascript:;">
						<div class="media-left">
							<i class="fa fa-bug media-object bg-silver-darker"></i>
						</div>
						<div class="media-body">
							<h6 class="media-heading">Server Error Reports <i class="fa fa-exclamation-circle text-danger"></i></h6>
							<div class="text-muted f-s-11">3 minutes ago</div>
						</div>
					</a>
				</li>
				<li class="media">
					<a href="javascript:;">
						<div class="media-left">
							<img src="{% static '/assets/core/img/user/user-1.jpg' %}" class="media-object" alt="" />
							<i class="fab fa-facebook-messenger text-primary media-object-icon"></i>
						</div>
						<div class="media-body">
							<h6 class="media-heading">John Smith</h6>
							<p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
							<div class="text-muted f-s-11">25 minutes ago</div>
						</div>
					</a>
				</li>
				<li class="media">
					<a href="javascript:;">
						<div class="media-left">
							<img src="{% static '/assets/core/img/user/user-2.jpg' %}" class="media-object" alt="" />
							<i class="fab fa-facebook-messenger text-primary media-object-icon"></i>
						</div>
						<div class="media-body">
							<h6 class="media-heading">Olivia</h6>
							<p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
							<div class="text-muted f-s-11">35 minutes ago</div>
						</div>
					</a>
				</li>
				<li class="media">
					<a href="javascript:;">
						<div class="media-left">
							<i class="fa fa-plus media-object bg-silver-darker"></i>
						</div>
						<div class="media-body">
							<h6 class="media-heading"> New User Registered</h6>
							<div class="text-muted f-s-11">1 hour ago</div>
						</div>
					</a>
				</li>
				<li class="media">
					<a href="javascript:;">
						<div class="media-left">
							<i class="fa fa-envelope media-object bg-silver-darker"></i>
							<i class="fab fa-google text-warning media-object-icon f-s-14"></i>
						</div>
						<div class="media-body">
							<h6 class="media-heading"> New Email From John</h6>
							<div class="text-muted f-s-11">2 hour ago</div>
						</div>
					</a>
				</li>
				<li class="dropdown-footer text-center">
					<a href="javascript:;">View more</a>
				</li>
			</ul>
		</li>
		<li class="dropdown navbar-user">
			<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
				<img src="{% static '/assets/core/img/user/user-13.jpg' %}" alt="" /> 
				<span class="d-none d-md-inline">{{ user.username }}</span> <b class="caret"></b>
			</a>
			<div class="dropdown-menu dropdown-menu-right">
				<a href="javascript:;" class="dropdown-item">Edit Profile</a>
				<a href="javascript:;" class="dropdown-item">Account</a>
				<div class="dropdown-divider"></div>
				<a href="{% url 'core:logout' %}" class="dropdown-item"><span class="fa fa-power-off pull-right"></span>Log Out</a>
			</div>
		</li>
	</ul>
	<!-- end header navigation right -->
</div>
<!-- end #header -->

application/core/templates/layout/includes/sidebar.html
{% load staticfiles %}
<!-- begin #sidebar -->
<div id="sidebar" class="sidebar">
	<!-- begin sidebar scrollbar -->
	<div data-scrollbar="true" data-height="100%">
		<!-- begin sidebar user -->
		<ul class="nav">
			<li class="nav-profile">
				<a href="javascript:;" data-toggle="nav-profile">
					<div class="image">
						<img src="{% static '/assets/core/img/user/user-13.jpg' %}" alt="" />
					</div>
					<div class="info">
						<b class="caret pull-right"></b>
						{{ user.get_full_name }}
						<small>{{ user.groups.all.0.name }}</small>
					</div>
				</a>
			</li>
			<li>
				<ul class="nav nav-profile">
                    <li><a href="javascript:;"><i class="fa fa-edit"></i> Edit Profile</a></li>
                    <li><a href="javascript:;"><i class="fa fa-user"></i> Account</a></li>
                </ul>
			</li>
		</ul>
		<!-- end sidebar user -->
		<!-- begin sidebar nav -->
		<ul class="nav">
			<li class="{% if request.resolver_match.url_name == 'dashboard' %} active {% endif %} ">
				<a href="{% url 'dashboard:dashboard' %}">
				    <i class="fa fa-th-large"></i>
				    <span>Dashboard</span>
			    </a>
			</li>
			<li class="has-sub {% if request.resolver_match.url_name == 'theater' or request.resolver_match.url_name == 'organization' %} active {% endif %}">
				<a href="javascript:;">
					<b class="caret"></b>
					<i class="fa fa-film"></i> 
					<span>Theaters</span>
				</a>
				<ul class="sub-menu">
				    <li class="{% if request.resolver_match.url_name == 'theater' %} active {% endif %}"><a href="{% url 'theater:theater' %}">Theaters</a></li>
				    <li class="{% if request.resolver_match.url_name == 'organization' %} active {% endif %} "><a href="{% url 'theater:organization' %}">Theater Organization</a></li>
				</ul>
			</li>
			<li class="has-sub {% if request.resolver_match.url_name == 'movie' or request.resolver_match.url_name == 'movie-title' or request.resolver_match.url_name == 'movie-title-lookup' %} active {% endif %} ">
				<a href="javascript:;">
			        <b class="caret"></b>
				    <i class="fa fa-play"></i>
				    <span>Movies</span> 
				</a>
				<ul class="sub-menu">
					<li class="{% if request.resolver_match.url_name == 'movie' %} active {% endif %} "><a href="{% url 'movie:movie' %}">Movies</a></li>
					<li class="{% if request.resolver_match.url_name == 'movie-title' %} active {% endif %} "><a href="{% url 'movie:movie-title' %}">Movie Title Bank</a></li>
					<li class="{% if request.resolver_match.url_name == 'movie-title-lookup' %} active {% endif %} "><a href="{% url 'movie:movie-title-lookup' %}">Orphaned Movie Titles</a></li>
				</ul>
			</li>
			<li class="{% if request.resolver_match.url_name == 'feed' %} active {% endif %}">
				<a href="{% url 'feed:feed' %}">
					<i class="fa fa-list"></i>
				    <span>Feeds</span> 
				</a>
			</li>
			<li class="has-sub {% if request.resolver_match.url_name == 'pesopay' or request.resolver_match.url_name == 'paynamics' or request.resolver_match.url_name == 'migs' or request.resolver_match.url_name == 'ipay88' or request.resolver_match.url_name == 'option' %} active {% endif %}">
				<a href="javascript:;">
			        <b class="caret"></b>
				    <i class="fa fa-credit-card"></i>
				    <span>Payment Settings</span> 
				</a>
				<ul class="sub-menu">
					<li class="{% if request.resolver_match.url_name == 'pesopay' %} active {% endif %}"><a href="{% url 'payment:pesopay' %}">Pesopay Payment Settings</a></li>
					<li class="{% if request.resolver_match.url_name == 'paynamics' %} active {% endif %}"><a href="{% url 'payment:paynamics' %}">Paynamics Payment Settings</a></li>
					<li class="{% if request.resolver_match.url_name == 'migs' %} active {% endif %}"><a href="{% url 'payment:migs' %}">MIGS Payment Settings</a></li>
					<li class="{% if request.resolver_match.url_name == 'ipay88' %} active {% endif %}"><a href="{% url 'payment:ipay88' %}">iPay88 Payment Settings</a></li>
					<li class="{% if request.resolver_match.url_name == 'option' %} active {% endif %}"><a href="{% url 'payment:option' %}">Payment Option Settings</a></li>
				</ul>
			</li>
			<li class="has-sub {% if request.resolver_match.url_name == 'transaction' or request.resolver_match.url_name == 'free-ticket' or request.resolver_match.url_name == 'promo' or request.resolver_match.url_name == 'csr-campaign' %} active {% endif %} ">
				<a href="javascript:;">
			        <b class="caret"></b>
				    <i class="fa fa-database"></i>
				    <span>Transactions</span>
				</a>
				<ul class="sub-menu">
					<li class="{% if request.resolver_match.url_name == 'transaction' %} active {% endif %}"><a href="{% url 'transaction:transaction' %}">Gmovies App Transactions</a></li>
			        <li class="{% if request.resolver_match.url_name == 'free-ticket' %} active {% endif %}"><a href="{% url 'transaction:free-ticket' %}">Gmovies Free Ticket</a></li>
			        <li class="{% if request.resolver_match.url_name == 'promo' %} active {% endif %}"><a href="{% url 'transaction:promo' %}">Gmovies Promo Transactions</a></li>
			        <li class="{% if request.resolver_match.url_name == 'csr-campaign' %} active {% endif %}"><a href="{% url 'transaction:csr-campaign' %}">CSR Campaign Transactions</a></li>
				</ul>
			</li>
			<li class="{% if request.resolver_match.url_name == 'client' %} active {% endif %}">
				<a href="{% url 'client:client' %}">
					<i class="fa fa-users"></i> 
					<span>Clients</span>
				</a>
			</li>
			<li class="has-sub {% if request.resolver_match.url_name == 'coming-soon' or request.resolver_match.url_name == 'blocked-screening' %} active {% endif %}">
			    <a href="javascript:;">
			        <b class="caret"></b>
			        <i class="fa fa-mars"></i>
			        <span>Assets</span>
			    </a>
				<ul class="sub-menu">
					<li class="{% if request.resolver_match.url_name == 'coming-soon' %} active {% endif %}"><a href="{% url 'asset:coming-soon' %}">Coming Soon Page</a></li>
					<li class="{% if request.resolver_match.url_name == 'blocked-screening' %} active {% endif %}"><a href="{% url 'asset:blocked-screening' %}">Blocked Screening</a></li>
				</ul>
			</li>
			<li class="has-sub {% if request.resolver_match.url_name == 'promo-setting' or request.resolver_match.url_name == 'system' or request.resolver_match.url_name == 'convenience-fee' or request.resolver_match.url_name == 'csr-campaign-setting' or request.resolver_match.url_name == 'service' %} active {% endif %}">
			    <a href="javascript:;">
			        <b class="caret"></b>
			        <i class="fa fa-cogs"></i>
				    <span>Settings</span>
				</a>
				<ul class="sub-menu">
				    <li class="{% if request.resolver_match.url_name == 'promo-setting' %} active {% endif %}"><a href="{% url 'setting:promo-setting' %}">Promos</a></li>
				    <li class="{% if request.resolver_match.url_name == 'system' %} active {% endif %}"><a href="{% url 'setting:system' %}">System Settings</a></li>
					<li class="{% if request.resolver_match.url_name == 'convenience-fee' %} active {% endif %}"><a href="{% url 'setting:convenience-fee' %}">Convenience Fee Settings</a></li>
				    <li class="{% if request.resolver_match.url_name == 'csr-campaign-setting' %} active {% endif %}"><a href="{% url 'setting:csr-campaign-setting' %}">CSR Campaign Settings</a></li>
				    <li class="{% if request.resolver_match.url_name == 'service' %} active {% endif %}"><a href="{% url 'setting:service' %}">Services Settings</a></li>
				</ul>
			</li>
	        <!-- begin sidebar minify button -->
			<li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
	        <!-- end sidebar minify button -->
		</ul>
		<!-- end sidebar nav -->
	</div>
	<!-- end sidebar scrollbar -->
</div>
<div class="sidebar-bg"></div>
<!-- end #sidebar -->