application/api/urls.py
from django.urls import path
from . import views

from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name = 'api'
urlpatterns = [
    path('v1', views.ApiV1.get, name='apiv1'),
    path('v2', views.ApiV2.as_view(), name='apiv2'),
    path('v3', views.ApiV3.as_view(), name='apiv3'),
    path('v4', views.ApiV4.as_view(), name='apiv4'),
    path('auth/', include('rest_framework.urls')),
    path('rest/', include(router.urls)),
]

application/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
	path('login/', views.Login.as_view(), name='login'),
	path('signoff/', views.logout_view, name='logout'),
	path('signup/', views.Signup.as_view(), name='signup'),
	path('success_signup/', views.SuccessSignup.as_view(), name='success_signup'),
	path('activate/<uidb64>/<token>/', views.activate, name='activate_email'),
    path('password/reset/', views.ResetPassword.as_view(), name='password_reset'),
    path('password/change/<token>/', views.ChangePassword.as_view(), name='password_change'),
]

application/core/models.py
import datetime
from django.db import models
from django.utils import timezone

class PasswordResets(models.Model):
	email = models.CharField(max_length=255)
	token = models.CharField(max_length=255)
	created_at 	= models.DateTimeField(timezone.now())

application/core/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.validators import validate_email
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if not user or not user.is_active:
                raise forms.ValidationError("Sorry, Invalid username or password. Please try again.")

        return self.cleaned_data

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class PasswordResetForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')

        if email and not User.objects.filter(email=email).exists():
            raise forms.ValidationError("We could'nt find that email address, Please try again.")

        return self.cleaned_data

class ChangePasswordForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, help_text='Required. Inform a valid and existing email address.')
    password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("We could'nt find that email address, Please try again!")
        if password != confirm_password:
            raise forms.ValidationError("Password not match. Please try again!")

        return self.cleaned_data

application/core/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import View
from django.utils import timezone
#from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.models import User
from .forms import *
from .models import *
from .core_helpers import *

#class handing for account login
class Login(View):
    template_name='core/login.html'

    def get(self, request, *args, **kwargs):
        form  = LoginForm()

        if request.user.is_authenticated:
            return redirect('/')

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = LoginForm(request.POST or None)
        username = request.POST['username']
        password = request.POST['password']

        if form.is_valid():
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)

                return HttpResponseRedirect('/')

        return render(request, self.template_name, {'form': form})

#class handing for account signup
class Signup(View):
    template_name = 'core/signup.html'

    def get(self, request, *args, **kwargs):
        form = SignupForm()
        if request.user.is_authenticated:
            return redirect('/')

        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = SignupForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            send_email(request, user, {}, 'Account activation email.', 'core/mail/account_activation.html')
            messages.success(request, 'Successfully registered, Please check activation link on your email.')

            return redirect('/accounts/success_signup/?email='+user.email)

        return render(request, self.template_name, {'form': form})

#class handling for successfull signup
class SuccessSignup(View):
    template_name = 'core/success_signup.html'
    
    def get(self, request, *args, **kwargs):
        email = request.GET['email']
        get_object_or_404(User, email=email)
        user =  User.objects.get(email=email)

        if user.is_active:
            raise Http404

        return render(request, self.template_name, {'email': email})

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        get_object_or_404(User, email=email)
        user =  User.objects.get(email=email)

        if user.is_active:
            raise Http404

        user = User.objects.get(email=email)
        send_email(request, user, {},'Account activation email.', 'core/mail/account_activation.html')
        messages.success(request, "Activation link successfully sent to your email "+email)

        return render(request, self.template_name, {'email': email})

#class handling for resetting password
class ResetPassword(View):
    template_name = 'core/password/reset_password.html'

    def get(self, request, *args, **kwargs):
        form = PasswordResetForm()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = PasswordResetForm(request.POST or None)
        email = request.POST['email']

        if form.is_valid():
            if User.objects.filter(email=email).exists():
                user = User.objects.get(email=email)
                token = generate_token.make_token(User.objects.get(email=email))
                email = email
                created_at = timezone.now()

                if PasswordResets.objects.filter(email=email).exists():
                    pr = PasswordResets.objects.get(email=email)
                    pr.email = email
                    pr.token = token
                    pr.created_at = created_at
                    pr.save()
                else:
                    pr = PasswordResets(email=email, token=token, created_at=created_at)
                    pr.save()

                messages.info(request, "Password reset link has been sent to your email.")
                data = {'token': token }
                send_email(request, user, {'token': token,},'Password reset link.', 'core/mail/password_reset.html')

        return render(request, self.template_name, {'form': form})

#class handling for resetting password
class ChangePassword(View):
    template_name = 'core/password/change_password.html'

    def get(self, request, token, *args, **kwargs):
        form = ChangePasswordForm()
        get_object_or_404(PasswordResets, token=token)

        return render(request, self.template_name, {'form': form})

    def post(self, request, token, *args, **kwargs):
        form = ChangePasswordForm(request.POST or None)
        email = request.POST['email']
        get_object_or_404(PasswordResets, token=token)

        if form.is_valid():
            user = User.objects.get(email=email)
            user.set_password(request.POST['password'])
            user.save()

            PasswordResets.objects.get(token=token).delete()
            messages.success(request, "You've successfully updated your password. You may now login with your new password!")

            return HttpResponseRedirect('/accounts/login/')

        return render(request, self.template_name, {'form': form})

#method for account activation via email link
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64).decode())
        user = User.objects.get(pk=uid)

        if user.is_active:
            raise Http404
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "You've Successfully activated your account.")

        return redirect('/')
    else:
        return render(request, 'account_activation_invalid.html')

#method for logout
@login_required
def logout_view(request):
    logout(request)

    return HttpResponseRedirect('/accounts/login')

application/core/templates/core/login.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Sign In | {{ settings.APP_NAME_TEXT }}{% endblock %}

{% block content %}
<div class="login login-with-news-feed">
    <!-- begin news-feed -->
    <div class="news-feed">
        <div class="news-image" style="background-image: url({% static '/assets/core/img/login-bg/login-bg-12.jpg' %})"></div>
        <div class="news-caption">
            <h4 class="caption-title"><b>{{ settings.APP_NAME }}</b> Admin App</h4>
            <p>
                Download the {{ settings.APP_NAME }} app for iPhone®, iPad®, and Android™. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
        </div>
    </div>
    <!-- end news-feed -->
    <!-- begin right-content -->
    <div class="right-content">
        <!-- begin login-header -->
        <div class="login-header">
            <div class="brand">
                <!-- <span class="logo"></span> --> <b>{{ settings.APP_NAME }}</b> Admin
                <small>For authorized administrator use only</small>
            </div>
            <div class="icon">
                <i class="fa fa-sign-in"></i>
            </div>
        </div>
        <!-- end login-header -->
        <!-- begin login-content -->
        <div class="login-content">
        	{% include settings.FORM_ERROR with form=form messages=messages %}
        	<form method="post" novalidate class="margin-bottom-0">
        		<input type="hidden" name="next" value="{{ next }}" />
			  	{% include settings.FORM_CORE with form=form %}
			  	<div class="login-buttons">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Sign me in</button>
                </div>
                <div class="m-t-20 m-b-40 p-b-40">
                    Not a member yet? Click <a href="register_v3.html">here</a> to register.<br>
                    Forgot password ? Click <a href="{% url 'core:password_reset' %}">here</a> to update password.
                </div>
                <hr />
                <p class="text-center">
                    &copy; {{ settings.APP_NAME }} Admin All Right Reserved 2018
                </p>
            </form>
        </div>
        <!-- end login-content -->
    </div>
    <!-- end right-container -->
</div>
{% endblock %}

application/core/templates/core/signup.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Sign Up | {{ settings.APP_NAME_TEXT }}{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">	
			<h3 class="page_header"><b>Sign Up</b></h3>
			<br>
			<p>Already have an account ? Then please <a href="{% url 'core:login' %}">Sign In</a></p>
			<br>
			{% include settings.FORM_ERROR with form=form messages=messages %}
		</div>
		<div class="col-md-3">	
			<form method="post" novalidate>
			  	{% include settings.FORM_CORE with form=form %}
			  	<div class="form-group">
			  		<button type="submit" class="btn btn-default">Sign Up <i class="fas fa-sign-in-alt"></i></button>
			  		<input type="hidden" name="next" value="{{ next }}" />
			  	</div>
			</form>	
		</div>
	</div>
</div>
{% endblock %}

application/core/templates/core/success_signup.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Success Signup | {{ settings.APP_NAME_TEXT }}{% endblock %}

{% block content %}
<div class="container">
	{% include settings.FORM_ERROR with messages=messages %}
	<br>
	<form novalidate method="POST" class="text-center">
		{% csrf_token %}
		<input type="hidden" name="email" maxlength="100" value="{{email}}">
		<button type="submit" class="btn btn-info btn-lg">Resend Activation Link <i class="fas fa-sync"></i></button>
	</form>
</div>
{% endblock %}